## Auto-MPG

![](https://factsanddetails.com/media/2/20111201-Molycorp%20REs-hev.png)

###The data is technical spec of cars, aiming to predict city fuel consumption
### (mile-per-gallon: MPG).

The features consist of
*   cylinders
*   displacement
*   horsepower
*   weight
*   acceleration
*   model year
*   original
*   car name

The output
mpg mile-per-gallon

[source] https://gist.githubusercontent.com/omarish/5687264/raw/7e5c814ce6ef33e25d5259c1fe79463c190800d9/mpg.csv

## ข้อ 1

In [1]:
import pandas as pd

url = 'https://gist.githubusercontent.com/omarish/5687264/raw/7e5c814ce6ef33e25d5259c1fe79463c190800d9/mpg.csv'
df_mpg = pd.read_csv(url)
print(df_mpg.shape)

# Display the first few rows of the DataFrame
display(df_mpg.head())

(398, 9)

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
0,18.0,8,307.0,130,3504,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350.0,165,3693,11.5,70,1,buick skylark 320
2,18.0,8,318.0,150,3436,11.0,70,1,plymouth satellite
3,16.0,8,304.0,150,3433,12.0,70,1,amc rebel sst
4,17.0,8,302.0,140,3449,10.5,70,1,ford torino

In [2]:
df_mpg['name'].value_counts()

name
ford pinto             6
ford maverick          5
amc matador            5
toyota corolla         5
amc hornet             4
                      ..
amc concord dl         1
volkswagen rabbit l    1
mazda glc custom l     1
mazda glc custom       1
chevy s-10             1
Name: count, Length: 305, dtype: int64

## ข้อ 2

In [3]:
import numpy as np
def clean_data(df):

  df = df.replace('?', np.nan)

  return df.dropna()

## ข้อ 3

In [4]:
df_mpg = clean_data(df_mpg)

df_mpg.drop('name', axis=1, inplace=True)

df_mpg

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin
0,18.0,8,307.0,130,3504,12.0,70,1
1,15.0,8,350.0,165,3693,11.5,70,1
2,18.0,8,318.0,150,3436,11.0,70,1
3,16.0,8,304.0,150,3433,12.0,70,1
4,17.0,8,302.0,140,3449,10.5,70,1
...,...,...,...,...,...,...,...,...
393,27.0,4,140.0,86,2790,15.6,82,1
394,44.0,4,97.0,52,2130,24.6,82,2
395,32.0,4,135.0,84,2295,11.6,82,1
396,28.0,4,120.0,79,2625,18.6,82,1
397,31.0,4,119.0,82,2720,19.4,82,1

## ข้อ 4

In [5]:
from sklearn.model_selection import train_test_split

df_mpg_encoded = df_mpg.copy()

# Assuming the target variable is 'mpg' and the features are the rest of the columns
X = df_mpg_encoded.drop('mpg', axis=1)
y = df_mpg_encoded['mpg']

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print("Training set shape (X_train, y_train):", X_train.shape, y_train.shape)
print("Testing set shape (X_test, y_test):", X_test.shape, y_test.shape)

Training set shape (X_train, y_train): (313, 7) (313,)
Testing set shape (X_test, y_test): (79, 7) (79,)

## ข้อ 5

In [6]:
from sklearn.linear_model import LinearRegression


model = LinearRegression()


model.fit(X_train, y_train)


coef = model.coef_
intercept = model.intercept_

eq = f"mpg = {intercept:.2f}"
for i, col in enumerate(X_train.columns):
    eq += f" + ({coef[i]:.2f} x {col})"
print(eq)

mpg = -18.50 + (-0.35 x cylinders) + (0.02 x displacement) + (-0.02 x horsepower) + (-0.01 x weight) + (0.04 x acceleration) + (0.77 x model_year) + (1.61 x origin)

## ข้อ 6

In [7]:
from sklearn.metrics import mean_squared_error, mean_absolute_error

y_pred = model.predict(X_test)


mse = mean_squared_error(y_test, y_pred)


mae = mean_absolute_error(y_test, y_pred)

print(f"Mean Squared Error (MSE) : {mse:.2f}")
print(f"Mean Absolute Error (MAE) : {mae:.2f}")

Mean Squared Error (MSE) : 10.71
Mean Absolute Error (MAE) : 2.42

## ข้อ 7
### อับโหลดข้อมูลจ 'transactions.csv' จาก google classroom

In [8]:
df_transactions = pd.read_csv('transactions.csv')
df_transactions

FileNotFoundError: [Errno 2] No such file or directory: 'transactions.csv'

## ข้อ 8

In [ ]:
print(df_transactions['P1'].mean(),df_transactions['P2'].mean(),df_transactions['P3'].mean())

9.23013698630137 16.53972602739726 27.44931506849315

## ข้อ 9

In [ ]:
from sklearn.linear_model import LinearRegression
import numpy as np

# Use the first 700 days of data
df_p1_700 = df_transactions.head(700).copy()

# Create lagged feature s(t)
df_p1_700['P1_lagged'] = df_p1_700['P1'].shift(1)

# Create target variable s(t+1)
df_p1_700['P1_target'] = df_p1_700['P1'].shift(-1)

# .....
# .....
# ....
# .....

NameError: name 'df_transactions' is not defined

## ข้อ 10

## ข้อ 11

In [ ]:
df_transactions

          Date  P1  P2  P3
0   2022-01-01   6  15  31
1   2022-01-02  19   0  30
2   2022-01-03  14  20   6
3   2022-01-04  10  21  17
4   2022-01-05   7  20  33
..         ...  ..  ..  ..
725 2023-12-27  16  21  35
726 2023-12-28   3   4  17
727 2023-12-29   0  12  31
728 2023-12-30   7  28  19
729 2023-12-31  16  17  29

[730 rows x 4 columns]

In [ ]:
ใช้ shift...

          Date   P2  P2_w(t)  P2_w(t-1)  P2_w(t+1)
2   2022-01-16  115    212.0       15.0        115
3   2022-01-23  109    115.0      212.0        109
4   2022-01-30  114    109.0      115.0        114
5   2022-02-06   78    114.0      109.0         78
6   2022-02-13   87     78.0      114.0         87
..         ...  ...      ...        ...        ...
100 2023-12-03  128     70.0       82.0        128
101 2023-12-10   91    128.0       70.0         91
102 2023-12-17  137     91.0      128.0        137
103 2023-12-24   95    137.0       91.0         95
104 2023-12-31   88     95.0      137.0         88

[103 rows x 5 columns]

## ข้อ 12

## ข้อ 13

Here's how to perform one-hot encoding on the 'car name' feature, focusing on the top 10 most frequent names and grouping the rest: